// PandaOS tool layer (MCP-style, our own). Read-only Base data + a non-custodial "draft" tool.
// Each tool returns { text } for the agent to read, optional { data } and optional { action }.
import { fmtUsd, ageText, short, isAddress, parseGtActions, parseYieldActions, evalAction, keyPrice, buyCost } from "./engine/panda.js";

const BS = "https://base.blockscout.com/api/v2";
const GT = "https://api.geckoterminal.com/api/v2/networks/base";
const DS = "https://api.dexscreener.com";
const GP = "https://api.gopluslabs.io/api/v1/token_security/8453";
const RPC = "https://mainnet.base.org";
const n = (v: any) => { const x = parseFloat(String(v ?? "")); return Number.isFinite(x) ? x : 0; };

async function J(u: string, ms = 13000) { const c = new AbortController(); const t = setTimeout(() => c.abort(), ms); try { const r = await fetch(u, { signal: c.signal, headers: { Accept: "application/json" } }); clearTimeout(t); return r.ok ? await r.json() : { _err: r.status }; } catch (e: any) { clearTimeout(t); return { _err: String(e?.message || e) }; } }
async function rpc(method: string, params: any[] = []) { try { const r = await fetch(RPC, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params }) }); return (await r.json()).result; } catch { return null; } }

export type ToolResult = { text: string; data?: any; action?: any };
export type Tool = { name: string; group: string; desc: string; params: string; run: (a: any) => Promise<ToolResult> };

export const TOOLS: Tool[] = [
  { name: "network_stats", group: "base", desc: "live Base network stats", params: "{}", run: async () => { const s = await J(`${BS}/stats`); if (!s || s._err) return { text: "Base stats unreachable" }; return { text: `Base mainnet: ${n(s.total_transactions).toLocaleString("en-US")} txns total, ${n(s.transactions_today).toLocaleString("en-US")} today, gas ${n(s.gas_prices?.average).toFixed(4)} gwei, ETH $${n(s.coin_price).toLocaleString("en-US")}, avg block ${(n(s.average_block_time) / 1000).toFixed(2)}s`, data: s }; } },
  { name: "gas", group: "base", desc: "current Base gas price", params: "{}", run: async () => { const s = await J(`${BS}/stats`); return { text: s?._err ? "gas unreachable" : `Base gas: ${n(s.gas_prices?.average).toFixed(4)} gwei` }; } },
  { name: "balance", group: "wallet", desc: "ETH balance of an address", params: '{ address }', run: async (a) => { const ad = (a.address || "").trim(); if (!isAddress(ad)) return { text: "need a valid 0x address" }; const h = await rpc("eth_getBalance", [ad, "latest"]); const e = h ? Number(BigInt(h)) / 1e18 : null; return { text: e == null ? "balance unreachable" : `${short(ad)} holds ${e.toFixed(5)} ETH` }; } },
  { name: "holdings", group: "wallet", desc: "token holdings of an address by USD", params: '{ address }', run: async (a) => { const ad = (a.address || "").trim(); if (!isAddress(ad)) return { text: "need a valid 0x address" }; const j = await J(`${BS}/addresses/${ad}/token-balances`); if (!Array.isArray(j)) return { text: "holdings unreachable" }; const rows = j.filter((x: any) => x.token && x.value).map((x: any) => { const d = n(x.token.decimals) || 18; const amt = Number(BigInt(x.value)) / 10 ** d; return { sym: x.token.symbol || "?", amt, usd: n(x.token.exchange_rate) * amt }; }).sort((p: any, q: any) => q.usd - p.usd).slice(0, 12); return { text: rows.length ? `${short(ad)} holdings:\n` + rows.map((r: any) => `  ${r.sym} ${r.amt.toFixed(4)}${r.usd ? " (" + fmtUsd(r.usd) + ")" : ""}`).join("\n") : "no indexed tokens", data: rows }; } },
  { name: "scan_new", group: "discovery", desc: "freshly launched Base pools, agent-scored", params: "{}", run: async (a) => { const j = await J(`${GT}/new_pools?include=base_token&page=1`); const acts = parseGtActions(j).map((x: any) => ({ ...x, ...evalAction(x, n(a.capital) || 1000) })).sort((p: any, q: any) => q.fit - p.fit).slice(0, 10); if (!acts.length) return { text: "scan unreachable or empty" }; return { text: "fresh on Base:\n" + acts.map((x: any) => `  [${x.verdict} ${x.fit}] ${x.title} ${fmtUsd(x.liq)} liq, ${ageText(x.createdAt)} old`).join("\n"), data: acts }; } },
  { name: "trending", group: "discovery", desc: "trending Base pools, scored", params: "{}", run: async (a) => { const j = await J(`${GT}/trending_pools?include=base_token&page=1`); const acts = parseGtActions(j).map((x: any) => ({ ...x, ...evalAction(x, 1000) })).sort((p: any, q: any) => q.fit - p.fit).slice(0, 10); return { text: acts.length ? "trending on Base:\n" + acts.map((x: any) => `  [${x.verdict} ${x.fit}] ${x.title} ${fmtUsd(x.liq)} liq`).join("\n") : "trending unreachable", data: acts }; } },
  { name: "yields", group: "discovery", desc: "top Base yield strategies (DefiLlama)", params: "{}", run: async () => { const j = await J("https://yields.llama.fi/pools"); const ys = parseYieldActions(j); return { text: ys.length ? "top Base yields:\n" + ys.slice(0, 10).map((y: any) => `  ${y.title} ${y.apy.toFixed(1)}% APY, ${fmtUsd(y.tvl)} TVL (${y.name})`).join("\n") : "yields unreachable", data: ys }; } },
  { name: "inspect", group: "discovery", desc: "security + market for a token", params: "{ token }", run: async (a) => { const ad = (a.token || "").trim(); if (!isAddress(ad)) return { text: "need a valid 0x token" }; const [gp, m, hc] = await Promise.all([J(`${GP}?contract_addresses=${ad}`), J(`${DS}/latest/dex/tokens/${ad}`), J(`${BS}/tokens/${ad}/counters`)]); const out: string[] = ["inspect " + short(ad)]; const pairs = (m && m.pairs) || []; const best = pairs.sort((x: any, y: any) => n(y.liquidity?.usd) - n(x.liquidity?.usd))[0]; if (best) out.push(`  ${best.baseToken?.symbol || "?"}: ${fmtUsd(n(best.liquidity?.usd))} liq, ${fmtUsd(n(best.volume?.h24))} vol24, ${n(best.priceChange?.h24).toFixed(1)}% 24h`); if (hc?.token_holders_count) out.push(`  holders: ${n(hc.token_holders_count).toLocaleString("en-US")}`); const r = gp?.result && Object.values(gp.result)[0] as any; if (r) out.push(`  honeypot ${String(r.is_honeypot) === "1" ? "YES" : "no"}, tax ${(n(r.buy_tax) * 100).toFixed(0)}%/${(n(r.sell_tax) * 100).toFixed(0)}%, ${String(r.is_open_source) === "1" ? "verified" : "unverified"}`); return { text: out.join("\n"), data: { gp: r, market: best } }; } },
  { name: "curve", group: "pandaex", desc: "pandaEX bonding-curve key price/cost", params: "{ supply, amount }", run: async (a) => { const s = Math.max(0, parseInt(a.supply) || 0), amt = Math.max(1, parseInt(a.amount) || 1); return { text: `pandaEX: next key @ supply ${s} = ${keyPrice(s).toFixed(6)} $POS; buy ${amt} = ${buyCost(s, amt).toFixed(6)} $POS` }; } },
  { name: "draft_action", group: "execute", desc: "draft a non-custodial action for the user to approve in their own wallet", params: "{ summary, token }", run: async (a) => { const token = (a.token || "").trim(); const link = isAddress(token) ? "https://dexscreener.com/base/" + token : "https://aerodrome.finance"; return { text: "drafted: " + (a.summary || "action") + ". approve it in your own wallet (PandaOS never signs).", action: { summary: a.summary || "action", token: isAddress(token) ? token : "", link } }; } }
];
export const TOOL_GROUPS = ["base", "wallet", "discovery", "pandaex", "execute"];
export const byName = (nm: string) => TOOLS.find((t) => t.name === nm);
